server:
  port: 8888
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

family:
  family-name: "happy family"
  father:
    name: albert
    age: 19
  mother:
    alias:
      -lovely
      -ailice
  child:
    name: zimug
    age: 4
  friends:
    - hobby: football
      sex: male
    - hobby: basketball
      sex: female
